configfile: "workflow/config.json"

ARIO_DIR = config["ARIO_DIR"]
INPUT_DIR = config['INPUT_DIR']
OUTPUT_DIR = config['OUTPUT_DIR']
FINAL_DIR = config['LONG_TERM_DIR']
REGIONS = config['REGIONS']
TYPES = config['TYPES']
FLOOD_INT = config['FLOOD_INT']
PSI = config['PSI']
INV_TAU = config['INV_TAU']
FLOOD_GDP_SHARE_FILE = config['FLOOD_GDP_SHARE_FILE']

RUNS = expand(FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indicators.json", region=REGIONS, stype=TYPES, flood=FLOOD_INT, psi=PSI, inv=INV_TAU)

TEST_RUN_ROW = expand(FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indicators.json", region=REGIONS[0], stype=TYPES[0], flood=FLOOD_INT[0], psi=PSI[0], inv=INV_TAU[0])

TEST_RUN_FULL = expand(FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indicators.json", region=REGIONS[0], stype=TYPES[1], flood=FLOOD_INT[0], psi=PSI[0], inv=INV_TAU[0])

rule test:
    input:
        TEST_RUN_ROW, TEST_RUN_FULL

rule all:
    input:
        RUNS

rule mv_to_final:
    input:
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indexes.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/classic_demand_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/final_demand_unmet_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_X_max_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_XVA_max_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/limiting_stocks_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/overprodvector_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_demand_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_prod_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_events.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_params.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulation.log",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indicators.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/treated_df.feather",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/treated_df_loss.feather"
    params:
        final_dir = FINAL_DIR
    output:
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indexes.json",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/classic_demand_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/final_demand_unmet_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_X_max_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_XVA_max_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/limiting_stocks_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/overprodvector_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_demand_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_prod_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_events.json",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_params.json",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulation.log",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indicators.json",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/treated_df.feather",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/treated_df_loss.feather"
    shell:
        """
        mkdir -p {config[FINAL_DIR]}+"{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}/
        cp {config[OUTPUT_DIR]}+"{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}/* {config[FINAL_DIR]}+"{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}/
        """

rule indicators:
    input:
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indexes.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/classic_demand_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/final_demand_unmet_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_X_max_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_XVA_max_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/limiting_stocks_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/overprodvector_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_demand_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_prod_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_events.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_params.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulation.log"
    output:
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indicators.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/treated_df.feather",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/treated_df_loss.feather"
    conda:
        "ario3"
    resources:
        mem_mb=15000,
        disk_mb=500
    shell:
        """
        nice -n 5 python {config[ARIO_DIR]}/scripts/indicator_from_folder.py '{config[OUTPUT_DIR]}{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}/'
        """

rule run_RoW:
    input:
        mrio = INPUT_DIR + "mrio_{region}.pkl",
        event_template = INPUT_DIR + "event_template.json",
        params_file = INPUT_DIR + "params.json",
        mrio_params = INPUT_DIR + "mrio_params.json"
    output:
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indexes.json",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/classic_demand_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/final_demand_unmet_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_X_max_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_XVA_max_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/limiting_stocks_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/overprodvector_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_demand_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_prod_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_events.json",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_params.json",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulation.log"
    conda:
        "ario3"
    resources:
        mem_mb=3000,
        disk_mb=50
    params:
        ario_dir = ARIO_DIR,
        input_dir = INPUT_DIR,
        output_dir = OUTPUT_DIR,
        flood_gdp = FLOOD_GDP_SHARE_FILE
    shell:
        """
        nice -n 5 python {config[ARIO_DIR]}/scripts/mono_run.py {wildcards.region} {input.params_file} {wildcards.psi} {wildcards.inv} RoW {wildcards.flood} {params.input_dir} {params.output_dir} {params.flood_gdp} {input.event_template} {input.mrio_params}
        """

rule run_Full:
    input:
        mrio = INPUT_DIR + "mrio_full.pkl",
        event_template = INPUT_DIR + "event_template.json",
        params_file = INPUT_DIR + "params.json",
        mrio_params = INPUT_DIR + "mrio_params.json"
    output:
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/indexes.json",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/classic_demand_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/final_demand_unmet_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_X_max_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/iotable_XVA_max_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/limiting_stocks_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/overprodvector_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_demand_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/rebuild_prod_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_events.json",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulated_params.json",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}/simulation.log"
    #benchmark:
    #    OUTPUT_DIR + "benchmarks/run_{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}.benchmark.txt"
    resources:
        mem_mb=4000,
        disk_mb=500
    conda:
        "ario3"
    params:
        input_dir = INPUT_DIR,
        output_dir = OUTPUT_DIR,
        flood_gdp = FLOOD_GDP_SHARE_FILE
    shell:
        """
        nice -n 5 python {config[ARIO_DIR]}/scripts/mono_run.py {wildcards.region} {input.params_file} {wildcards.psi} {wildcards.inv} Full {wildcards.flood} {params.input_dir} {params.output_dir} {params.flood_gdp} {input.event_template} {input.mrio_params}
        """

rule mrio_full:
    input:
        mrio_file = INPUT_DIR + "IOT_2019_ixi.zip",
        sector_aggreg_file = INPUT_DIR + "133_74_sector_aggregation_exiobase3.ods",
        sector_renaming_file = INPUT_DIR + "sector_renaming_74.json"
    conda:
        "ario3"
    output:
        INPUT_DIR + "mrio_full.pkl"
#    benchmark:
#        OUTPUT_DIR + "benchmarks/mrio_full.pkl.benchmark.txt"
    resources:
        mem_mb=6000,
        disk_mb=2000
    shell:
        """
        nice -n 5 python {config[ARIO_DIR]}/scripts/aggreg_exio3.py -o {output} {input.mrio_file} {input.sector_aggreg_file} {input.sector_renaming_file}
        """

rule mrio_region:
    input:
        mrio_file = INPUT_DIR + "IOT_2019_ixi.zip",
        sector_aggreg_file = INPUT_DIR + "133_74_sector_aggregation_exiobase3.ods",
        sector_renaming_file = INPUT_DIR + "sector_renaming_74.json",
        region_aggreg_file = INPUT_DIR + "aggreg/{region}_aggreg.json"
    conda:
        "ario3"
    output:
        INPUT_DIR + "mrio_{region}.pkl"
#    benchmark:
#        OUTPUT_DIR + "benchmarks/mrio_{region}.pkl.benchmark.txt"
    resources:
        mem_mb=6000,
        disk_mb=2000
    shell:
        """
        nice -n 5 python {config[ARIO_DIR]}/scripts/aggreg_exio3.py -o {output} {input.mrio_file} {input.sector_aggreg_file} {input.sector_renaming_file} {input.region_aggreg_file}
        """

rule region_aggreg_dict:
    output:
        INPUT_DIR + "aggreg/{region}_aggreg.json"
    run:
        import json
        dic = {
            "aggregates":{str(wildcards.region):str(wildcards.region)},
            "missing":"RoW"
        }
        with open(output[0],'w') as f:
            json.dump(dic, f)
