configfile: "workflow/config.json"

ARIO_DIR = config["ARIO_DIR"]
INPUT_DIR = config['INPUT_DIR']
OUTPUT_DIR = config['OUTPUT_DIR']
FINAL_DIR = config['LONG_TERM_DIR']
REGIONS = config['REGIONS']
TYPES = config['TYPES']
FLOOD_INT = config['FLOOD_INT']
FLOOD_DMG = config['FLOOD_DMG']
PSI = config['PSI']
INV_TAU = config['INV_TAU']
INV_TIME = config['INV_TIME']
FLOOD_GDP_SHARE_FILE = config['FLOOD_GDP_SHARE_FILE']

def raw_dmg_runs():
    if FINAL_DIR == OUTPUT_DIR:
        return expand(OUTPUT_DIR+"{region}_type_{stype}_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indicators.json", region=REGIONS, stype=TYPES, flood=FLOOD_DMG, psi=PSI, inv=INV_TAU, inv_t=INV_TIME)
    else :
        return expand(FINAL_DIR+"{region}_type_{stype}_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indicators.json", region=REGIONS, stype=TYPES, flood=FLOOD_DMG, psi=PSI, inv=INV_TAU, inv_t=INV_TIME)

def runs():
    if FINAL_DIR == OUTPUT_DIR:
        return expand(OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indicators.json", region=REGIONS, stype=TYPES, flood=FLOOD_INT, psi=PSI, inv=INV_TAU, inv_t=INV_TIME)
    else :
        return expand(FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indicators.json", region=REGIONS, stype=TYPES, flood=FLOOD_INT, psi=PSI, inv=INV_TAU, inv_t=INV_TIME)

RAW_DMG_RUNS = raw_dmg_runs()

RUNS = runs()

PROD_INDICATORS_RUNS = expand(OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/prod_chg.json", region=REGIONS, stype=TYPES, flood=FLOOD_INT, psi=PSI, inv=INV_TAU, inv_t=INV_TIME)

TEST_RUN_FULL = expand(OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indicators.json", region=REGIONS[0], stype=TYPES[0], flood=FLOOD_INT[0], psi=PSI[0], inv=INV_TAU[0], inv_t=INV_TIME[0])

rule all_raw:
    input:
        RAW_DMG_RUNS

rule all_intensity:
    input:
        RUNS

rule test:
    input:
        TEST_RUN_FULL

rule all_prod_indicators:
    input:
        PROD_INDICATORS_RUNS

rule all_indicators_json:
    input:
        expand(OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indicators.json", region=REGIONS, stype=TYPES, flood=FLOOD_INT, psi=PSI, inv=INV_TAU, inv_t=INV_TIME)


rule prod_indicators:
    # Obsolete !
    input:
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/treated_df_limiting.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/treated_df_loss.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/prod_df.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/c_demand_df.parquet",
    conda:
        "ario3"
    output:
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/prod_chg.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/fd_loss.json"
    shell:
        """
        nice -n 10 python {config[ARIO_DIR]}/scripts/other_indicators.py '{config[OUTPUT_DIR]}{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}_inv_time_{wildcards.inv_t}/' -o {config[OUTPUT_DIR]}{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}_inv_time_{wildcards.inv_t}/
        """

rule mv_to_final:
    input:
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indexes.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/classic_demand_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/final_demand_unmet_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_X_max_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_XVA_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/limiting_stocks_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/overprodvector_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_demand_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_prod_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_events.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_params.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulation.log",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indicators.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/treated_df_limiting.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/treated_df_loss.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/prod_df.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/c_demand_df.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/prod_chg.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/fd_loss.json"
    params:
        final_dir = FINAL_DIR,
        output_dir = OUTPUT_DIR
    resources:
        mem_mb = 500,
        vmem_mb = 500
    output:
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indexes.json",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/classic_demand_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/final_demand_unmet_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_X_max_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_XVA_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/limiting_stocks_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/overprodvector_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_demand_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_prod_record",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_events.json",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_params.json",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulation.log",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indicators.json",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/treated_df_limiting.parquet",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/treated_df_loss.parquet",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/prod_df.parquet",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/c_demand_df.parquet",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/prod_chg.json",
        FINAL_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/fd_loss.json"
    shell:
        """
        mkdir -p {params.final_dir}{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}_inv_time_{wildcards.inv_t}/
        cp {params.output_dir}{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}_inv_time_{wildcards.inv_t}/* {params.final_dir}{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}_inv_time_{wildcards.inv_t}/
        """

rule indicators:
    input:
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indexes.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/classic_demand_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/final_demand_unmet_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_X_max_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_XVA_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/limiting_stocks_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/overprodvector_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_demand_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_prod_record",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_events.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_params.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulation.log"
    output:
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indicators.json",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/treated_df_limiting.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/treated_df_loss.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/prod_df.parquet",
        OUTPUT_DIR+"{region}_type_{stype}_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/c_demand_df.parquet",
    conda:
        "ario3"
    resources:
        vmem_mb=15000,
        mem_mb = 12000,
        disk_mb=500
    shell:
        """
        nice -n 10 python {config[ARIO_DIR]}/scripts/indicator_from_folder.py '{config[OUTPUT_DIR]}{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}_inv_time_{wildcards.inv_t}/'
        """

rule run_RoW:
    input:
        mrio = INPUT_DIR + "mrio_{region}.pkl",
        event_template = INPUT_DIR + "event_template.json",
        params_file = INPUT_DIR + "params.json",
        mrio_params = INPUT_DIR + "mrio_params.json"
    output:
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indexes.json",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/classic_demand_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/final_demand_unmet_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_X_max_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_XVA_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/limiting_stocks_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/overprodvector_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_demand_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_prod_record",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_events.json",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_params.json",
        OUTPUT_DIR+"{region}_type_RoW_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulation.log"
    conda:
        "ario3"
    resources:
        mem_mb=4000,
        disk_mb=50
    benchmark:
        OUTPUT_DIR + "benchmarks/run_{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}.benchmark.txt"
    params:
        ario_dir = ARIO_DIR,
        input_dir = INPUT_DIR,
        output_dir = OUTPUT_DIR,
        flood_gdp = FLOOD_GDP_SHARE_FILE
    shell:
        """
        nice -n 10 python {config[ARIO_DIR]}/scripts/mono_run.py {wildcards.region} {input.params_file} {wildcards.psi} {wildcards.inv} RoW {wildcards.flood} {params.input_dir} {params.output_dir} {params.flood_gdp} {input.event_template} {input.mrio_params} {wildcards.inv_t}
        """

rule run_Full_dmg_raw:
    input:
        mrio = INPUT_DIR + "mrio_full.pkl",
        event_template = INPUT_DIR + "event_template.json",
        params_file = INPUT_DIR + "params.json",
        mrio_params = INPUT_DIR + "mrio_params.json"
    wildcard_constraints:
        flood="\d+"
    output:
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indexes.json",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/classic_demand_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/final_demand_unmet_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_X_max_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_XVA_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/limiting_stocks_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/overprodvector_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_demand_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_prod_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_events.json",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_params.json",
        OUTPUT_DIR+"{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulation.log"
    benchmark:
        OUTPUT_DIR + "benchmarks/run_{region}_type_Full_qdmg_raw_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}.benchmark.txt"
    resources:
        vmem_mb=3000,
        mem_mb=2000,
        disk_mb=500
    conda:
        "ario3"
    params:
        input_dir = INPUT_DIR,
        output_dir = OUTPUT_DIR,
        flood_gdp = FLOOD_GDP_SHARE_FILE
    shell:
        """
        nice -n 10 python {config[ARIO_DIR]}/scripts/mono_run_dmg.py {wildcards.region} {input.params_file} {wildcards.psi} {wildcards.inv} Full {wildcards.flood} {params.input_dir} {params.output_dir} {input.event_template} {input.mrio_params} {wildcards.inv_t}
        """

rule run_Full:
    input:
        mrio = INPUT_DIR + "mrio_full.pkl",
        event_template = INPUT_DIR + "event_template.json",
        params_file = INPUT_DIR + "params.json",
        mrio_params = INPUT_DIR + "mrio_params.json"
    wildcard_constraints:
        flood="max|min|\d{1,2}%"
    output:
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/indexes.json",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/classic_demand_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/final_demand_unmet_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_X_max_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/iotable_XVA_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/limiting_stocks_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/overprodvector_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_demand_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/rebuild_prod_record",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_events.json",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulated_params.json",
        OUTPUT_DIR+"{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}/simulation.log"
    benchmark:
        OUTPUT_DIR + "benchmarks/run_{region}_type_Full_qdmg_{flood}_Psi_{psi}_inv_tau_{inv}_inv_time_{inv_t}.benchmark.txt"
    resources:
        vmem_mb=3000,
        mem_mb=2000,
        disk_mb=500
    conda:
        "ario3"
    params:
        input_dir = INPUT_DIR,
        output_dir = OUTPUT_DIR,
        flood_gdp = FLOOD_GDP_SHARE_FILE
    shell:
        """
        nice -n 10 python {config[ARIO_DIR]}/scripts/mono_run.py {wildcards.region} {input.params_file} {wildcards.psi} {wildcards.inv} Full {wildcards.flood} {params.input_dir} {params.output_dir} {params.flood_gdp} {input.event_template} {input.mrio_params} {wildcards.inv_t}
        """

rule mrio_full:
    input:
        mrio_file = INPUT_DIR + "IOT_2019_ixi.zip",
        sector_aggreg_file = INPUT_DIR + "133_74_sector_aggregation_exiobase3.ods",
        sector_renaming_file = INPUT_DIR + "sector_renaming_74.json"
    conda:
        "ario3"
    output:
        INPUT_DIR + "mrio_full.pkl"
    benchmark:
        OUTPUT_DIR + "benchmarks/mrio_full.pkl.benchmark.txt"
    resources:
        vmem_mb=6000,
        mem_mb=5000,
        disk_mb=2000
    shell:
        """
        nice -n 10 python {config[ARIO_DIR]}/scripts/aggreg_exio3.py -o {output} {input.mrio_file} {input.sector_aggreg_file} {input.sector_renaming_file}
        """

rule mrio_region:
    input:
        mrio_file = INPUT_DIR + "IOT_2019_ixi.zip",
        sector_aggreg_file = INPUT_DIR + "133_74_sector_aggregation_exiobase3.ods",
        sector_renaming_file = INPUT_DIR + "sector_renaming_74.json",
        region_aggreg_file = INPUT_DIR + "aggreg/{region}_aggreg.json"
    conda:
        "ario3"
    output:
        INPUT_DIR + "mrio_{region}.pkl"
    benchmark:
        OUTPUT_DIR + "benchmarks/mrio_{region}.pkl.benchmark.txt"
    resources:
        vmem_mb=6000,
        mem_mb=5000,
        disk_mb=2000
    shell:
        """
        nice -n 10 python {config[ARIO_DIR]}/scripts/aggreg_exio3.py -o {output} {input.mrio_file} {input.sector_aggreg_file} {input.sector_renaming_file} {input.region_aggreg_file}
        """

rule region_aggreg_dict:
    output:
        INPUT_DIR + "aggreg/{region}_aggreg.json"
    run:
        import json
        dic = {
            "aggregates":{str(wildcards.region):str(wildcards.region)},
            "missing":"RoW"
        }
        with open(output[0],'w') as f:
            json.dump(dic, f)
